version: "3"

services: 

  go-clean-template:
    build:
      context: ./
      dockerfile: ./Dockerfile-development
    container_name: go-clean-template
    env_file: .env
    depends_on: 
      - psql_db
    networks: 
      - default
    ports:
      - 3000:3000
    volumes:
      - .:/go/src/github.com/Blackmocca/go-clean-template
  
  psql_db:
    build:
      dockerfile: ./Dockerfile
      context: ./docker-script/postgres
    restart: always
    container_name: psql_db
    networks: 
      - default
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_example

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    networks: 
      - default
    ports:
      - 8080:8080

networks:
  default:
    external:
      name: localdev