FROM golang:1.17

ENV GO111MODULE=on
ENV ADDR=0.0.0.0
ENV TZ=Asia/Bangkok

RUN mkdir -p /go/src/github.com/Blackmocca/go-clean-template
WORKDIR /go/src/github.com/Blackmocca/go-clean-template

# Move to project folder
WORKDIR /go/src/github.com/Blackmocca/go-clean-template

COPY . . 
RUN go get -u github.com/githubnemo/CompileDaemon
RUN go mod tidy     

RUN  go build -o  /go/src/github.com/Blackmocca/go-clean-template/tmp/app main.go

EXPOSE 3000
EXPOSE 3100

ENTRYPOINT CompileDaemon -include=go.mod -log-prefix=false -color=true -build="go build -o ./tmp/app main.go" -command="./tmp/app" 
