version: "3"

services: 

  app:
    build:
      context: ./
      dockerfile: ./Dockerfile-development
    container_name: app
    env_file: .env
    depends_on:
      - psql_db
    networks: 
      - dbservice
    ports:
      - 3000:3000
    volumes:
      - .:/go/src/app
  
  psql_db:
    build:
      dockerfile: ./Dockerfile
      context: ./docker-script/postgres
    restart: always
    container_name: psql_db
    networks: 
      - dbservice
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB_PROD=app_example
      - POSTGRES_DB_TEST=app_example_test

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    networks: 
      - dbservice
    ports:
      - 8080:8080

networks:
  dbservice:
    driver: bridge