FROM golang:1.13-rc-alpine AS builder

RUN apk --no-cache add git
 
ENV GO111MODULE=on

RUN mkdir -p /go/src/app
WORKDIR /go/src/app

COPY go.mod .

RUN go get github.com/pilu/fresh
RUN go mod tidy

COPY . . 

RUN go build -o ./tmp/app

ENTRYPOINT fresh
