version: "3"

services: 

  app:
    build:
      context: ./
      dockerfile: ./Dockerfile-development
    container_name: app
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - ./main.go:/go/src/app/main.go
