// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/organize.proto

package proto_models

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DefaultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DefaultRequest) Reset() {
	*x = DefaultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_organize_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultRequest) ProtoMessage() {}

func (x *DefaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_organize_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultRequest.ProtoReflect.Descriptor instead.
func (*DefaultRequest) Descriptor() ([]byte, []int) {
	return file_proto_organize_proto_rawDescGZIP(), []int{0}
}

type OrganizeData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AliasName    string `protobuf:"bytes,3,opt,name=alias_name,json=aliasName,proto3" json:"alias_name,omitempty"`
	OrgType      string `protobuf:"bytes,4,opt,name=org_type,json=orgType,proto3" json:"org_type,omitempty"`
	OrderNo      int64  `protobuf:"varint,5,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	PrivateTelNo string `protobuf:"bytes,6,opt,name=private_tel_no,json=privateTelNo,proto3" json:"private_tel_no,omitempty"`
	CreatedAt    string `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt    string `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *OrganizeData) Reset() {
	*x = OrganizeData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_organize_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrganizeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizeData) ProtoMessage() {}

func (x *OrganizeData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_organize_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizeData.ProtoReflect.Descriptor instead.
func (*OrganizeData) Descriptor() ([]byte, []int) {
	return file_proto_organize_proto_rawDescGZIP(), []int{1}
}

func (x *OrganizeData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrganizeData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrganizeData) GetAliasName() string {
	if x != nil {
		return x.AliasName
	}
	return ""
}

func (x *OrganizeData) GetOrgType() string {
	if x != nil {
		return x.OrgType
	}
	return ""
}

func (x *OrganizeData) GetOrderNo() int64 {
	if x != nil {
		return x.OrderNo
	}
	return 0
}

func (x *OrganizeData) GetPrivateTelNo() string {
	if x != nil {
		return x.PrivateTelNo
	}
	return ""
}

func (x *OrganizeData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrganizeData) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type FetchOrganizeByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FetchOrganizeByIdRequest) Reset() {
	*x = FetchOrganizeByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_organize_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchOrganizeByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOrganizeByIdRequest) ProtoMessage() {}

func (x *FetchOrganizeByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_organize_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOrganizeByIdRequest.ProtoReflect.Descriptor instead.
func (*FetchOrganizeByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_organize_proto_rawDescGZIP(), []int{2}
}

func (x *FetchOrganizeByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FetchOrganizeByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Organize *OrganizeData `protobuf:"bytes,1,opt,name=organize,proto3" json:"organize,omitempty"`
}

func (x *FetchOrganizeByIdResponse) Reset() {
	*x = FetchOrganizeByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_organize_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchOrganizeByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOrganizeByIdResponse) ProtoMessage() {}

func (x *FetchOrganizeByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_organize_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOrganizeByIdResponse.ProtoReflect.Descriptor instead.
func (*FetchOrganizeByIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_organize_proto_rawDescGZIP(), []int{3}
}

func (x *FetchOrganizeByIdResponse) GetOrganize() *OrganizeData {
	if x != nil {
		return x.Organize
	}
	return nil
}

var File_proto_organize_proto protoreflect.FileDescriptor

var file_proto_organize_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x10, 0x0a,
	0x0e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0xeb, 0x01, 0x0a, 0x0c, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x12, 0x24, 0x0a, 0x0e, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x65, 0x6c, 0x5f, 0x6e, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x54, 0x65, 0x6c, 0x4e, 0x6f, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x2a, 0x0a,
	0x18, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x65, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4c, 0x0a, 0x19, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69,
	0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6f,
	0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x65, 0x32, 0x64, 0x0a, 0x08, 0x4f, 0x72, 0x67, 0x61, 0x6e,
	0x69, 0x7a, 0x65, 0x12, 0x58, 0x0a, 0x11, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4f, 0x72, 0x67, 0x61,
	0x6e, 0x69, 0x7a, 0x65, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x65, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x65, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x10, 0x5a,
	0x0e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_organize_proto_rawDescOnce sync.Once
	file_proto_organize_proto_rawDescData = file_proto_organize_proto_rawDesc
)

func file_proto_organize_proto_rawDescGZIP() []byte {
	file_proto_organize_proto_rawDescOnce.Do(func() {
		file_proto_organize_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_organize_proto_rawDescData)
	})
	return file_proto_organize_proto_rawDescData
}

var file_proto_organize_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_organize_proto_goTypes = []interface{}{
	(*DefaultRequest)(nil),            // 0: proto.DefaultRequest
	(*OrganizeData)(nil),              // 1: proto.OrganizeData
	(*FetchOrganizeByIdRequest)(nil),  // 2: proto.FetchOrganizeByIdRequest
	(*FetchOrganizeByIdResponse)(nil), // 3: proto.FetchOrganizeByIdResponse
}
var file_proto_organize_proto_depIdxs = []int32{
	1, // 0: proto.FetchOrganizeByIdResponse.organize:type_name -> proto.OrganizeData
	2, // 1: proto.Organize.FetchOrganizeById:input_type -> proto.FetchOrganizeByIdRequest
	3, // 2: proto.Organize.FetchOrganizeById:output_type -> proto.FetchOrganizeByIdResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_organize_proto_init() }
func file_proto_organize_proto_init() {
	if File_proto_organize_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_organize_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_organize_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrganizeData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_organize_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchOrganizeByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_organize_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchOrganizeByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_organize_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_organize_proto_goTypes,
		DependencyIndexes: file_proto_organize_proto_depIdxs,
		MessageInfos:      file_proto_organize_proto_msgTypes,
	}.Build()
	File_proto_organize_proto = out.File
	file_proto_organize_proto_rawDesc = nil
	file_proto_organize_proto_goTypes = nil
	file_proto_organize_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrganizeClient is the client API for Organize service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrganizeClient interface {
	FetchOrganizeById(ctx context.Context, in *FetchOrganizeByIdRequest, opts ...grpc.CallOption) (*FetchOrganizeByIdResponse, error)
}

type organizeClient struct {
	cc grpc.ClientConnInterface
}

func NewOrganizeClient(cc grpc.ClientConnInterface) OrganizeClient {
	return &organizeClient{cc}
}

func (c *organizeClient) FetchOrganizeById(ctx context.Context, in *FetchOrganizeByIdRequest, opts ...grpc.CallOption) (*FetchOrganizeByIdResponse, error) {
	out := new(FetchOrganizeByIdResponse)
	err := c.cc.Invoke(ctx, "/proto.Organize/FetchOrganizeById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrganizeServer is the server API for Organize service.
type OrganizeServer interface {
	FetchOrganizeById(context.Context, *FetchOrganizeByIdRequest) (*FetchOrganizeByIdResponse, error)
}

// UnimplementedOrganizeServer can be embedded to have forward compatible implementations.
type UnimplementedOrganizeServer struct {
}

func (*UnimplementedOrganizeServer) FetchOrganizeById(context.Context, *FetchOrganizeByIdRequest) (*FetchOrganizeByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchOrganizeById not implemented")
}

func RegisterOrganizeServer(s *grpc.Server, srv OrganizeServer) {
	s.RegisterService(&_Organize_serviceDesc, srv)
}

func _Organize_FetchOrganizeById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchOrganizeByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizeServer).FetchOrganizeById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Organize/FetchOrganizeById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizeServer).FetchOrganizeById(ctx, req.(*FetchOrganizeByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Organize_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Organize",
	HandlerType: (*OrganizeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchOrganizeById",
			Handler:    _Organize_FetchOrganizeById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/organize.proto",
}
