// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	models "github.com/BlackMocca/go-clean-template/models"
	mock "github.com/stretchr/testify/mock"
)

// UserUsecaseInf is an autogenerated mock type for the UserUsecaseInf type
type UserUsecaseInf struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *UserUsecaseInf) Create(_a0 *models.User) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.User) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
