// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// OrganizeHandler is an autogenerated mock type for the OrganizeHandler type
type OrganizeHandler struct {
	mock.Mock
}

// CreateOrg provides a mock function with given fields: c
func (_m *OrganizeHandler) CreateOrg(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchAll provides a mock function with given fields: c
func (_m *OrganizeHandler) FetchAll(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchOneById provides a mock function with given fields: c
func (_m *OrganizeHandler) FetchOneById(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewOrganizeHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrganizeHandler creates a new instance of OrganizeHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrganizeHandler(t mockConstructorTestingTNewOrganizeHandler) *OrganizeHandler {
	mock := &OrganizeHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
